# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Agilize.me
tagline:          'Blog'
description:      'Inteligência Artificial para todos.'
url:              https://agilize.me/blog
baseurl:          /

author:
  name:           'Marcio Stabile'
  url:            https://twitter.com/Marcio_Stabile

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/agilize-me
