# Dependencies
highlighter:      rouge

# Setup
title:            Agilize.me
tagline:          'Blog'
description:      'Inteligência Artificial para todos.'
url:              http://blog.agilize.me
baseurl:          /

authors:
  marcio:
    name: 'Marcio Fernando Stabile Junior'
    display_name: 'Marcio Stabile'
    gravatar: c66919cb194f96c696c1da0c47354a6a
    url: https://github.com/mfstabile
  barbara:
    name: Barbara Tieko Agena
    display_name: Barbara Tieko
  thiago:
    name: Thiago Henrique Dias Araújo
    display_name: Thiago Araujo
    url: https://github.com/thdaraujo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/agilize-me
