# Dependencies
highlighter:      pygments

# Setup
title:            Agilize.me
tagline:          'Blog'
description:      'Inteligência Artificial para todos.'
url:              https://agilize.me/blog
baseurl:          /

authors:
  marcio:
    name: 'Marcio Stabile'
    display_name: 'Marcio Stabile'
    gravatar: c66919cb194f96c696c1da0c47354a6a
    url: https://github.com/mfstabile
  barbara:
    name: Barbara Tieko Agena
    display_name: Barbara Tieko

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/agilize-me
